name: 'Automatically close stale issues'

on:
  schedule:
    # Runs every day at 8:00 AM CET
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f # v10.2.0
        with:
          # See documentation at https://github.com/actions/stale?tab=readme-ov-file#all-options
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-issue-message: |
            This issue has been automatically marked as stale because it has not had recent activity and has the `need-info` label.

            It will be closed if no further activity occurs within 3 days.

          stale-pr-message: |
            This pull request has been automatically marked as stale because it has not had recent activity and has the `need-info` label.

            It will be closed if no further activity occurs within 3 days.

          stale-issue-label: 'stale'
          close-issue-label: 'automatically closed'
          only-labels: 'need-info'
          days-before-issue-stale: 14
          days-before-issue-close: 3
